name: Run Javascript Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run build --if-present
        DATABASE_URL=$DATABASE_URL
        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
        echo "SECRET=$SECRET" >> $GITHUB_ENV
        npm test
      env:
        CI: true
